const { PR_STATES } = require('../../github/pr-state');

function buildPRBody(state) {
  const lines = [
    `## AI Pipeline Execution Report`,
    ``,
    `**Issue:** #${state.issue.id} — ${state.issue.title}`,
    `**Status:** ${state.status}`,
    `**PR State:** ${state._prState || PR_STATES.OPEN}`,
    ``,
    `---`,
    ``,
    `### Architecture Decision Summary`,
    `- **Summary:** ${state.architecture?.summary || 'N/A'}`,
    `- **Flow:** ${state.architecture?.flow || 'N/A'}`,
    `- **Decisions:** ${(state.architecture?.decisions || []).join(', ')}`,
    ``,
    `---`,
    ``,
    `### Affected Files`,
    ``,
  ];

  for (const f of (state.files || [])) {
    lines.push(`- \`${f.path}\``);
  }

  lines.push(``, `---`, ``, `### Execution Log Summary`);

  if (state._executionLog) {
    lines.push(`\`\`\``);
    lines.push(state._executionLog.substring(0, 2000));
    lines.push(`\`\`\``);
  } else {
    lines.push(`⚠️ NO EXECUTION DATA — THIS PR IS INVALID`);
  }

  lines.push(``, `---`, ``, `### Validation Report`);
  lines.push(`- **Status:** ${state.validation?.status || 'N/A'}`);
  lines.push(`- **Errors:** ${(state.validation?.errors || []).join('; ') || 'None'}`);

  if (state._reviewGate) {
    lines.push(``, `---`, ``, `### Review Gate`);
    lines.push(`- **Review Status:** ${state._reviewGate.status}`);
    lines.push(`- **Execution Verified:** ${state._reviewGate.executionVerified}`);
    lines.push(`- **Tests Verified:** ${state._reviewGate.testsVerified}`);
    lines.push(`- **Next Action:** ${state._reviewGate.nextAction}`);
  }

  lines.push(``, `---`, ``, `### Test Results`);
  if (state._testResults) {
    lines.push(`\`\`\``);
    lines.push(state._testResults);
    lines.push(`\`\`\``);
  } else {
    lines.push(`⚠️ No test results attached.`);
  }

  lines.push(``, `> This PR was auto-generated by AI Dev Orchestration System.`);
  lines.push(`> PR without execution data is INVALID.`);

  return lines.join('\n');
}

async function prCreateNode(state) {
  const startTime = Date.now();
  console.error(`[PR-CREATE] Building PR with execution data`);

  try {
    const prBody = buildPRBody(state);

    if (!state._executionLog) {
      console.error(`[PR-CREATE] WARNING: No execution data — PR is INVALID per issue #103 rules`);
    }

    const prUrl = state.pr?.url || `https://github.com/sandbox/pull/${state.issue.id || 'new'}`;
    const timestamp = new Date().toISOString();

    const executionTrace = {
      node: 'pr-create',
      timestamp,
      duration: Date.now() - startTime,
      status: 'success',
      hasExecutionData: !!state._executionLog,
      prState: state._prState || PR_STATES.OPEN
    };

    console.error(`[PR-CREATE] PR created: ${prUrl}`);
    console.error(`[PR-CREATE] PR state: ${state._prState || PR_STATES.OPEN}`);
    console.error(`[PR-CREATE] Has execution data: ${!!state._executionLog}`);

    return {
      pr: {
        url: prUrl,
        body: prBody,
        state: state._prState || PR_STATES.OPEN,
        fixAttempts: state.pr?.fixAttempts || 0,
        status: 'open'
      },
      files: [...(state.files || []), {
        path: `shared/pr-body.md`,
        content: prBody
      }],
      execution: {
        status: 'completed',
        current_node: 'pr-create',
        attempts: state.execution?.attempts || 0,
        trace: [...(state.execution?.trace || []), executionTrace]
      }
    };
  } catch (err) {
    console.error(`[PR-CREATE] Error: ${err.message}`);
    const timestamp = new Date().toISOString();
    const executionTrace = {
      node: 'pr-create',
      timestamp,
      duration: Date.now() - startTime,
      status: 'failed',
      error: err.message
    };

    return {
      pr: { url: null, status: 'failed', fixAttempts: state.pr?.fixAttempts || 0 },
      execution: {
        status: 'failed',
        current_node: 'pr-create',
        attempts: (state.execution?.attempts || 0) + 1,
        trace: [...(state.execution?.trace || []), executionTrace]
      }
    };
  }
}

module.exports = { prCreateNode };
